"""empty message

Revision ID: 08303cffab13
Revises: 51ce53df6b5f
Create Date: 2023-03-28 12:10:12.334438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08303cffab13'
down_revision = '51ce53df6b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_opportunities')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.TIME(), nullable=False))

    op.create_table('_alembic_tmp_opportunities',
    sa.Column('opp_id', sa.INTEGER(), nullable=False),
    sa.Column('nonprofit_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=6), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['nonprofit_id'], ['nonprofits.nonprofit_id'], ),
    sa.PrimaryKeyConstraint('opp_id')
    )
    # ### end Alembic commands ###
